import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import QueryWrapper from "./components/QueryWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryWrapper>
          <div className="flex md:max-w-screen-2xl md:px-24 px-2 mx-auto">
            <div className="w-1/3 bg-slate-50 pt-10 px-3 min-h-screen hidden md:block">
              <Sidebar />
            </div>
            <div className="w-full">
              <Header links={[]} />
              <div className="md:p-10 p-2">{children}</div>
            </div>
          </div>
        </QueryWrapper>
      </body>
    </html>
  );
}
